baseURL = "https://affectionate-bhaskara-5ad158.netlify.app/"
languageCode = "en-us"
title = "IanWhitney.com"
theme="archie"

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3
